server:
  port: 8080
spring:
  application:
    name: "backend-test"
cors:
  allowed-origins: "*"
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: "/swagger-ui/index.html"