apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: namespace-test
  name: backend-jobs-deployment
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: backend-jobs-api
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: backend-jobs-api
    spec:
      containers:
        - name: backend-jobs-api
          image: 486655662493.dkr.ecr.us-east-1.amazonaws.com/backend-jobs:latest
          resources:
            requests:
              memory: "4Gi"
              cpu: "2"
            limits:
              memory: "16Gi"
              cpu: "2"
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  namespace: namespace-test
  name: backend-jobs-service
spec:
  ports:
    - name: http
      protocol: TCP
      targetPort: 8081
      port: 8091
  type: NodePort
  selector:
    app.kubernetes.io/name: backend-jobs-api
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-jobs-autoscaler
  namespace: namespace-test
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend-jobs-deployment
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 100
          periodSeconds: 15
    scaleUp:
      stabilizationWindowSeconds: 180
      policies:
        - type: Pods
          value: 1
          periodSeconds: 15
      selectPolicy: Max
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
